<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 5.0.1.dev1 (Python 3.9.1 on win32)" generated="20220918 11:14:29.728" rpa="false" schemaversion="3">
<suite id="s1" name="Test" source="C:\Users\Shaimaa Ali\PycharmProjects\pythonProject\TestCases\Test.robot">
<test id="s1-t1" name="Open link page" line="8">
<kw name="open">
<arg>${URL}</arg>
<arg>chrome</arg>
<msg timestamp="20220918 11:14:29.763" level="FAIL">No keyword with name 'open' found.</msg>
<status status="FAIL" starttime="20220918 11:14:29.763" endtime="20220918 11:14:29.763"/>
</kw>
<status status="FAIL" starttime="20220918 11:14:29.761" endtime="20220918 11:14:29.765">No keyword with name 'open' found.</status>
</test>
<status status="FAIL" starttime="20220918 11:14:29.731" endtime="20220918 11:14:29.767"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test">Test</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220918 11:14:29.759" level="ERROR">Error in file 'C:\Users\Shaimaa Ali\PycharmProjects\pythonProject\TestCases\Test.robot' on line 2: Importing library 'SeleniumLibrary' failed: ModuleNotFoundError: No module named 'SeleniumLibrary'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\Shaimaa Ali\AppData\Local\Programs\Python\Python39\Scripts
  c:\users\shaimaa ali\appdata\local\programs\python\python39\python39.zip
  c:\users\shaimaa ali\appdata\local\programs\python\python39\DLLs
  c:\users\shaimaa ali\appdata\local\programs\python\python39\lib
  c:\users\shaimaa ali\appdata\local\programs\python\python39
  c:\users\shaimaa ali\appdata\local\programs\python\python39\lib\site-packages</msg>
</errors>
</robot>
